language: node_js
node_js:
- 8
- 10.4.1
install:
- cp package.json package.json.bak
- npm run install:peers:ci
- npm install
script:
- npm run lint
- npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run build && mv package.json.bak package.json
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
